"Filed out from Dolphin Smalltalk"!

Exception subclass: #WebsideException
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WebsideException guid: (GUID fromString: '{0bccb83b-5d71-46ce-90ab-3fd303168aa4}')!

WebsideException comment: ''!

!WebsideException categoriesForClass!Kernel-Exception Handling! !

!WebsideException methodsFor!

defaultAction!

isResumable
	^true! !

!WebsideException categoriesForMethods!
defaultAction!public! !
isResumable!public! !
!

